FROM docker.io/library/node:20-slim

RUN apt-get update && apt-get install -y openssl procps --no-install-recommends && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

CMD ["npm", "run", "start:dev"]